/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_daqo_dbinfo_Dlllink */

#ifndef _Included_com_daqo_dbinfo_Dlllink
#define _Included_com_daqo_dbinfo_Dlllink
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: INSTANCE */
/* Inaccessible static: dbstatus */
/* Inaccessible static: runhome */
/*
 * Class:     com_daqo_dbinfo_Dlllink
 * Method:    startdb
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_daqo_dbinfo_Dlllink_startdb
  (JNIEnv *, jobject);

/*
 * Class:     com_daqo_dbinfo_Dlllink
 * Method:    closedb
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_daqo_dbinfo_Dlllink_closedb
  (JNIEnv *, jobject);

/*
 * Class:     com_daqo_dbinfo_Dlllink
 * Method:    getenvvar
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_daqo_dbinfo_Dlllink_getenvvar
  (JNIEnv *, jobject);

/*
 * Class:     com_daqo_dbinfo_Dlllink
 * Method:    getTableInfo
 * Signature: ([B[B[[B[I[B)I
 */
JNIEXPORT jint JNICALL Java_com_daqo_dbinfo_Dlllink_getTableInfo
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jobjectArray, jintArray, jbyteArray);

/*
 * Class:     com_daqo_dbinfo_Dlllink
 * Method:    openTableInfo
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_com_daqo_dbinfo_Dlllink_openTableInfo
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_daqo_dbinfo_Dlllink
 * Method:    closeTableInfo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_daqo_dbinfo_Dlllink_closeTableInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_daqo_dbinfo_Dlllink
 * Method:    readdata
 * Signature: ([[B)I
 */
JNIEXPORT jint JNICALL Java_com_daqo_dbinfo_Dlllink_readdata
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_daqo_dbinfo_Dlllink
 * Method:    readRecorders
 * Signature: ([B[B[B[B[B[IZ)I
 */
JNIEXPORT jint JNICALL Java_com_daqo_dbinfo_Dlllink_readRecorders
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jintArray, jboolean);

/*
 * Class:     com_daqo_dbinfo_Dlllink
 * Method:    insertARecord
 * Signature: ([[B)I
 */
JNIEXPORT jint JNICALL Java_com_daqo_dbinfo_Dlllink_insertARecord
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_daqo_dbinfo_Dlllink
 * Method:    updateARecord
 * Signature: ([[B[II)I
 */
JNIEXPORT jint JNICALL Java_com_daqo_dbinfo_Dlllink_updateARecord
  (JNIEnv *, jobject, jobjectArray, jintArray, jint);

/*
 * Class:     com_daqo_dbinfo_Dlllink
 * Method:    removeARecord
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_daqo_dbinfo_Dlllink_removeARecord
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_daqo_dbinfo_Dlllink
 * Method:    reCall
 * Signature: ([[B[[B)I
 */
JNIEXPORT jint JNICALL Java_com_daqo_dbinfo_Dlllink_reCall
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     com_daqo_dbinfo_Dlllink
 * Method:    reloadRtdb
 * Signature: ([[B)I
 */
JNIEXPORT jint JNICALL Java_com_daqo_dbinfo_Dlllink_reloadRtdb
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_daqo_dbinfo_Dlllink
 * Method:    reloadMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_daqo_dbinfo_Dlllink_reloadMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_daqo_dbinfo_Dlllink
 * Method:    sendMsgToFert
 * Signature: (IB[B)I
 */
JNIEXPORT jint JNICALL Java_com_daqo_dbinfo_Dlllink_sendMsgToFert
  (JNIEnv *, jobject, jint, jbyte, jbyteArray);

/*
 * Class:     com_daqo_dbinfo_Dlllink
 * Method:    sendMsgToWeb
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_daqo_dbinfo_Dlllink_sendMsgToWeb
  (JNIEnv *, jobject);

/*
 * Class:     com_daqo_dbinfo_Dlllink
 * Method:    sendEventMsg
 * Signature: ([B[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_daqo_dbinfo_Dlllink_sendEventMsg
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_daqo_dbinfo_Dlllink
 * Method:    getAMaxMinVal
 * Signature: ([B[B[BB)I
 */
JNIEXPORT jint JNICALL Java_com_daqo_dbinfo_Dlllink_getAMaxMinVal
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyte);

/*
 * Class:     com_daqo_dbinfo_Dlllink
 * Method:    execproc
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_daqo_dbinfo_Dlllink_execproc
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_daqo_dbinfo_Dlllink
 * Method:    makeBcp
 * Signature: ([B[B[B[B[BZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_daqo_dbinfo_Dlllink_makeBcp
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
