######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 12 16:57:51 2016
######################################################################

TEMPLATE = lib
TARGET = dmessagebox
DEPENDPATH += . debug
INCLUDEPATH += .
DESTDIR = $(NBENV)/lib

DEFINES += UI_DMESSAGEBOX_DLL
# Input
HEADERS += dmessagebox.h 
SOURCES += dmessagebox.cpp
RESOURCES += dmessagebox.qrc
