######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 22 11:09:03 2012
######################################################################

CONFIG  += ordered
TEMPLATE = subdirs

SUBDIRS = fesplatform fesshm fesdev fesapi msgengine fessvc  protocol/iec104 protocol/cdt protocol/iec101 protocol/iec101b protocol/modbust protocol/modbusdaqo fesmirror\
			fesstat fesoper fespara fesmsg festools rawview
					
