######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 16 09:53:25 2017
######################################################################

TEMPLATE = app
TARGET = convertini
DEPENDPATH += .
INCLUDEPATH += .
DESTDIR = $(NBENV)/bin
LIBS += -L$(NBENV)/lib -lrwini -lrwxml -lverapi
# Input
HEADERS += convertini.h
SOURCES += convertini.cpp main.cpp
FORMS += convertini.ui
RESOURCES = convertini.qrc